import type { StaticCompletionEntry } from '../../lib/types';

/**
 * Curated offline fallback dictionary of standard C++20 keywords,
 * core STL containers, algorithms, and algorithmic loop snippets.
 */
export const STATIC_CPP_COMPLETIONS: StaticCompletionEntry[] = [
  // --- C++20 Keywords ---
  { label: 'auto', kind: 'keyword', detail: 'keyword', documentation: 'Type deduction placeholder', insertText: 'auto ' },
  { label: 'const', kind: 'keyword', detail: 'keyword', documentation: 'Specifies that a value cannot be modified', insertText: 'const ' },
  { label: 'constexpr', kind: 'keyword', detail: 'keyword', documentation: 'Specifies that value or function can be evaluated at compile time', insertText: 'constexpr ' },
  { label: 'consteval', kind: 'keyword', detail: 'keyword', documentation: 'Produces an immediate function that must evaluate at compile time (C++20)', insertText: 'consteval ' },
  { label: 'concept', kind: 'keyword', detail: 'keyword', documentation: 'Defines a named set of constraints on template arguments (C++20)', insertText: 'concept ${1:Name} = ${2:condition};', isSnippet: true },
  { label: 'requires', kind: 'keyword', detail: 'keyword', documentation: 'Introduces a constraint or requires-expression (C++20)', insertText: 'requires ' },
  { label: 'template', kind: 'keyword', detail: 'keyword', documentation: 'Defines a parameterized class or function template', insertText: 'template <typename ${1:T}>\n' },
  { label: 'typename', kind: 'keyword', detail: 'keyword', documentation: 'Declares a template parameter or dependent type', insertText: 'typename ' },
  { label: 'struct', kind: 'keyword', detail: 'keyword', documentation: 'Defines a user-defined composite type with public default access', insertText: 'struct ${1:Name} {\n\t$0\n};', isSnippet: true },
  { label: 'class', kind: 'keyword', detail: 'keyword', documentation: 'Defines a user-defined composite type with private default access', insertText: 'class ${1:Name} {\npublic:\n\t$0\n};', isSnippet: true },
  { label: 'return', kind: 'keyword', detail: 'keyword', documentation: 'Returns from the current function', insertText: 'return $0;' },
  { label: 'nullptr', kind: 'keyword', detail: 'keyword', documentation: 'Null pointer literal constant', insertText: 'nullptr' },
  { label: 'static_cast', kind: 'keyword', detail: 'keyword', documentation: 'Performs compile-time verified type conversion', insertText: 'static_cast<${1:Type}>(${2:expression})', isSnippet: true },
  { label: 'sizeof', kind: 'keyword', detail: 'keyword', documentation: 'Yields the size in bytes of the object or type', insertText: 'sizeof(${1:expr})', isSnippet: true },
  { label: 'static_assert', kind: 'keyword', detail: 'keyword', documentation: 'Performs compile-time assertion checking', insertText: 'static_assert(${1:condition}, "${2:message}");', isSnippet: true },

  // --- Core STL Containers & Types ---
  {
    label: 'std::vector',
    kind: 'type',
    detail: 'class template',
    documentation: 'Dynamic contiguous array container from <vector>',
    insertText: 'std::vector<${1:int}> ${2:name};',
    isSnippet: true,
  },
  {
    label: 'std::string',
    kind: 'type',
    detail: 'typedef std::basic_string<char>',
    documentation: 'Standard character sequence container from <string>',
    insertText: 'std::string ${1:s};',
    isSnippet: true,
  },
  {
    label: 'std::unordered_map',
    kind: 'type',
    detail: 'class template',
    documentation: 'Hash-table based key-value associative container from <unordered_map>',
    insertText: 'std::unordered_map<${1:int}, ${2:int}> ${3:map};',
    isSnippet: true,
  },
  {
    label: 'std::unordered_set',
    kind: 'type',
    detail: 'class template',
    documentation: 'Hash-table based unique key container from <unordered_set>',
    insertText: 'std::unordered_set<${1:int}> ${2:set};',
    isSnippet: true,
  },
  {
    label: 'std::map',
    kind: 'type',
    detail: 'class template',
    documentation: 'Red-black tree based sorted associative container from <map>',
    insertText: 'std::map<${1:int}, ${2:int}> ${3:map};',
    isSnippet: true,
  },
  {
    label: 'std::set',
    kind: 'type',
    detail: 'class template',
    documentation: 'Red-black tree based sorted unique key container from <set>',
    insertText: 'std::set<${1:int}> ${2:set};',
    isSnippet: true,
  },
  {
    label: 'std::queue',
    kind: 'type',
    detail: 'container adapter',
    documentation: 'FIFO queue container adapter from <queue>',
    insertText: 'std::queue<${1:int}> ${2:q};',
    isSnippet: true,
  },
  {
    label: 'std::deque',
    kind: 'type',
    detail: 'class template',
    documentation: 'Double-ended queue container from <deque>',
    insertText: 'std::deque<${1:int}> ${2:dq};',
    isSnippet: true,
  },
  {
    label: 'std::stack',
    kind: 'type',
    detail: 'container adapter',
    documentation: 'LIFO stack container adapter from <stack>',
    insertText: 'std::stack<${1:int}> ${2:st};',
    isSnippet: true,
  },
  {
    label: 'std::priority_queue',
    kind: 'type',
    detail: 'container adapter',
    documentation: 'Max-heap priority queue from <queue>. Use std::greater for min-heap.',
    insertText: 'std::priority_queue<${1:int}> ${2:pq};',
    isSnippet: true,
  },
  {
    label: 'std::priority_queue (min-heap)',
    kind: 'snippet',
    detail: 'min-heap snippet',
    documentation: 'Min-heap priority queue using std::greater<T>',
    insertText: 'std::priority_queue<${1:int}, std::vector<${1:int}>, std::greater<${1:int}>> ${2:min_pq};',
    isSnippet: true,
  },
  {
    label: 'std::pair',
    kind: 'type',
    detail: 'struct template',
    documentation: 'Heterogeneous two-element tuple from <utility>',
    insertText: 'std::pair<${1:int}, ${2:int}>',
    isSnippet: true,
  },
  {
    label: 'std::tuple',
    kind: 'type',
    detail: 'class template',
    documentation: 'Fixed-size collection of heterogeneous values from <tuple>',
    insertText: 'std::tuple<${1:int}, ${2:int}, ${3:int}>',
    isSnippet: true,
  },
  {
    label: 'std::span',
    kind: 'type',
    detail: 'class template (C++20)',
    documentation: 'Non-owning contiguous sequence view from <span>',
    insertText: 'std::span<${1:const int}> ${2:view};',
    isSnippet: true,
  },

  // --- Algorithms & Utilities ---
  {
    label: 'std::sort',
    kind: 'function',
    detail: 'template <class RandomIt> void sort(...)',
    documentation: 'Sorts elements in range [first, last) in ascending order from <algorithm>',
    insertText: 'std::sort(${1:v}.begin(), ${1:v}.end());',
    isSnippet: true,
  },
  {
    label: 'std::ranges::sort',
    kind: 'function',
    detail: 'C++20 range algorithm',
    documentation: 'Sorts range using C++20 ranges from <algorithm>',
    insertText: 'std::ranges::sort(${1:container});',
    isSnippet: true,
  },
  {
    label: 'std::reverse',
    kind: 'function',
    detail: 'template <class BidirIt> void reverse(...)',
    documentation: 'Reverses the order of elements in range [first, last)',
    insertText: 'std::reverse(${1:v}.begin(), ${1:v}.end());',
    isSnippet: true,
  },
  {
    label: 'std::max',
    kind: 'function',
    detail: 'constexpr const T& max(const T& a, const T& b)',
    documentation: 'Returns the greater of the given values from <algorithm>',
    insertText: 'std::max(${1:a}, ${2:b})',
    isSnippet: true,
  },
  {
    label: 'std::min',
    kind: 'function',
    detail: 'constexpr const T& min(const T& a, const T& b)',
    documentation: 'Returns the smaller of the given values from <algorithm>',
    insertText: 'std::min(${1:a}, ${2:b})',
    isSnippet: true,
  },
  {
    label: 'std::swap',
    kind: 'function',
    detail: 'void swap(T& a, T& b)',
    documentation: 'Exchanges the values of a and b from <utility>',
    insertText: 'std::swap(${1:a}, ${2:b});',
    isSnippet: true,
  },
  {
    label: 'std::lower_bound',
    kind: 'function',
    detail: 'ForwardIt lower_bound(...)',
    documentation: 'Returns iterator pointing to first element not less than value from <algorithm>',
    insertText: 'std::lower_bound(${1:v}.begin(), ${1:v}.end(), ${2:val})',
    isSnippet: true,
  },
  {
    label: 'std::upper_bound',
    kind: 'function',
    detail: 'ForwardIt upper_bound(...)',
    documentation: 'Returns iterator pointing to first element greater than value from <algorithm>',
    insertText: 'std::upper_bound(${1:v}.begin(), ${1:v}.end(), ${2:val})',
    isSnippet: true,
  },
  {
    label: 'std::binary_search',
    kind: 'function',
    detail: 'bool binary_search(...)',
    documentation: 'Checks if element equivalent to target exists in sorted range',
    insertText: 'std::binary_search(${1:v}.begin(), ${1:v}.end(), ${2:target})',
    isSnippet: true,
  },
  {
    label: 'std::make_pair',
    kind: 'function',
    detail: 'constexpr pair<V1, V2> make_pair(T1&&, T2&&)',
    documentation: 'Creates a std::pair object with types deduced from arguments',
    insertText: 'std::make_pair(${1:first}, ${2:second})',
    isSnippet: true,
  },

  // --- Algorithmic Loop Snippets ---
  {
    label: 'for (indexed loop)',
    kind: 'snippet',
    detail: 'for (int i = 0; i < n; ++i)',
    documentation: 'Standard zero-indexed counting loop',
    insertText: 'for (int ${1:i} = 0; ${1:i} < ${2:n}; ++${1:i}) {\n\t$0\n}',
    isSnippet: true,
  },
  {
    label: 'for (range-based loop)',
    kind: 'snippet',
    detail: 'for (const auto& item : container)',
    documentation: 'Range-based for loop over elements by const reference',
    insertText: 'for (const auto& ${1:item} : ${2:container}) {\n\t$0\n}',
    isSnippet: true,
  },
  {
    label: 'for (mutable range loop)',
    kind: 'snippet',
    detail: 'for (auto& item : container)',
    documentation: 'Range-based for loop with mutable reference',
    insertText: 'for (auto& ${1:item} : ${2:container}) {\n\t$0\n}',
    isSnippet: true,
  },
  {
    label: 'while loop',
    kind: 'snippet',
    detail: 'while (condition)',
    documentation: 'Standard while loop block',
    insertText: 'while (${1:condition}) {\n\t$0\n}',
    isSnippet: true,
  },

  // --- Common DSA Problem Stubs ---
  {
    label: 'TreeNode struct',
    kind: 'snippet',
    detail: 'Binary tree node structure definition',
    documentation: 'Standard binary tree node definition used in tree problems',
    insertText:
      'struct TreeNode {\n\tint val;\n\tTreeNode *left;\n\tTreeNode *right;\n\tTreeNode() : val(0), left(nullptr), right(nullptr) {}\n\tTreeNode(int x) : val(x), left(nullptr), right(nullptr) {}\n\tTreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}\n};',
    isSnippet: true,
  },
  {
    label: 'ListNode struct',
    kind: 'snippet',
    detail: 'Singly linked list node structure definition',
    documentation: 'Standard singly linked list node definition used in linked list problems',
    insertText:
      'struct ListNode {\n\tint val;\n\tListNode *next;\n\tListNode() : val(0), next(nullptr) {}\n\tListNode(int x) : val(x), next(nullptr) {}\n\tListNode(int x, ListNode *next) : val(x), next(next) {}\n};',
    isSnippet: true,
  },
];
